name: Terraform Deployment (ACI)

on:
  workflow_run:
    workflows: ["Docker Build & Push"]  # Ensure this matches the name of your Docker workflow
    types:
      - completed

jobs:
  deploy-terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_ghcr_image_url: ghcr.io/${{ github.repository }}:latest
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Verify Secrets (Debugging Step)
        run: |
          echo "AZURE_CLIENT_ID: $AZURE_CLIENT_ID"
          echo "AZURE_SUBSCRIPTION_ID: $AZURE_SUBSCRIPTION_ID"
          echo "AZURE_TENANT_ID: $AZURE_TENANT_ID"
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Init
        working-directory: terraform-aci
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform-aci
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform-aci
        run: terraform apply -auto-approve
