name: deploy-with-terraform

on:
  workflow_run:
    workflows: ["build-and-push-docker"]
    types:
      - completed

jobs:
  deploy:
    name: Terraform Deploy to Azure ACI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-aci

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="ghcr_token=${{ secrets.GHCR_TOKEN }}" -var="ghcr_image_url=ghcr.io/${{ github.repository_owner }}/damcey-app:latest"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ghcr_token=${{ secrets.GHCR_TOKEN }}" -var="ghcr_image_url=ghcr.io/${{ github.repository_owner }}/damcey-app:latest"
